# Generated by Django 4.2.2 on 2023-08-17 10:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0007_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apartment_price',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='floor',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='floor_count',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='living_space',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='metro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть в формате: '+799999999'.", regex='^\\+7\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='price_per_square',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='rooms_count',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_of_construction',
            field=models.CharField(max_length=4),
        ),
    ]
