# Generated by Django 4.2.2 on 2023-08-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_page', '0008_alter_user_apartment_price_alter_user_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='evolution_type',
        ),
    ]
